name: Lighthouse

on: workflow_dispatch

jobs:

  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Lighthouse CI Action
      uses: treosh/lighthouse-ci-action@v9
      with:
        urls: |
          https://develop.calebstauffer.com
        uploadArtifacts: true # save results as an action artifacts
        temporaryPublicStorage: true # upload lighthouse report to the temporary storage
